export const SEARCH_MOVIE = "SEARCH_MOVIE";
export const START_REQUEST = "START_REQUEST";
export const FETCH_MOVIES_SUCCESS = "FETCH_MOVIES_SUCCESS";
export const FETCH_MOVIES_FAILURE = "FETCH_MOVIES_FAILURE";
export const START_MOVIE = "START_MOVIE_REQUEST";
export const FETCH_MOVIE = "FETCH_MOVIE_REQUEST";